name: GitHub Actions ãƒ‡ãƒ¢
run-name: ${{ github.actor }}ãŒGitHub Actionsã‚’ãƒ†ã‚¹ãƒˆã—ã¦ã„ã¾ã™âœˆ
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ”ã€€ãƒ–ãƒ©ãƒ³ãƒåã¯ ${{ github.ref }}ã€ãƒªãƒã‚¸ãƒˆãƒªåã¯ ${{ github.repository }} ã§ã™ã€‚"
    - name: ãƒªãƒã‚¸ãƒˆãƒªã®ã‚³ãƒ¼ãƒ‰ã‚’ãƒã‚§ãƒƒã‚¯ã‚¢ã‚¦ãƒˆã™ã‚‹
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ãƒªãƒã‚¸ãƒˆãƒª ${{ github.repository }}ãŒãƒ©ãƒ³ãƒŠãƒ¼ä¸Šã«ã‚¯ãƒ­ãƒ¼ãƒ³ã•ã‚Œã¾ã—ãŸã€‚"
    - name: ãƒªãƒã‚¸ãƒˆãƒªå†…ã®ãƒ•ã‚¡ã‚¤ãƒ«ã‚’ä¸€è¦§è¡¨ç¤º
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸã“ã®ã‚¸ãƒ§ãƒ–ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹ã¯ ${{ job.status }}ã§ã™ã€‚"
